[package]
name = "moirai-pump"
version = "0.8.6"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Event-pump runtime for Moirai job system"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/moirai"
repository = "https://github.com/PsichiX/moirai"
documentation = "https://docs.rs/moirai-pump"
readme = "../../README.md"

[dependencies]
moirai = { version = "0.8", path = "../_" }
flume = { version = "0.12", default-features = false, features = ["async"] }

[dev-dependencies]
pollster = { version = "0.4", features = ["macro"] }
