[package]
name = "moirai-durable"
version = "0.8.4"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Durable future support for Moirai job system"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/moirai"
repository = "https://github.com/PsichiX/moirai"
documentation = "https://docs.rs/moirai-durable"
readme = "../../README.md"

[dependencies]
moirai = { version = "0.8", path = "../_" }
intuicio-data = "0.52"
serde-intermediate = "1.6"
serde = { version = "1", features = ["derive"] }
